---
# Handlers for CPU optimization role

- name: reload_systemd
  systemd:
    daemon_reload: yes
  listen: reload_systemd

- name: update_grub_config
  command: update-grub
  when: ansible_os_family == "Debian"
  listen: update_grub_config

- name: update_grub_config
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_os_family == "RedHat"
  listen: update_grub_config
